1,7,Startup
9,11,Trapping START SHOT
12,18,Waiting for START SHOT
20,46,Making a SHOT
47,49,Pressure Control
51,54,Waiting for FOLLOW THROUGH
57,60,Waiting for RETRACT
70,71,Waiting for JOG SHOT
73,76,PARK VALVE
90,97,Making a JOG SHOT
100,112,Testing the VALVE
113,117,Waiting for RETRACT
149,153,Waiting for AT HOME
170,181,MANUAL MODE
