ren alarmsum.cpp alarmsum.cpp
ren array.cpp array.cpp
ren ascfloat.cpp ascfloat.cpp
ren asensor.cpp asensor.cpp
ren bitclass.cpp bitclass.cpp
ren callfile.cpp callfile.cpp
ren catclass.cpp catclass.cpp
ren chaxis.cpp chaxis.cpp
ren client.cpp client.cpp
ren color.cpp color.cpp
ren colorcl.cpp colorcl.cpp
ren computer.cpp computer.cpp
ren converta.cpp converta.cpp
ren copymach.cpp copymach.cpp
ren copypart.cpp copypart.cpp
ren current.cpp current.cpp
ren dateclas.cpp dateclas.cpp
ren dbsubs.cpp dbsubs.cpp
ren dcurve.cpp dcurve.cpp
ren dow.cpp dow.cpp
ren downsubs.cpp downsubs.cpp
ren downtime.cpp downtime.cpp
ren dstat.cpp dstat.cpp
ren dtotchar.cpp dtotchar.cpp
ren dynamic_file_name.cpp dynamic_file_name.cpp
ren error_ms.cpp error_ms.cpp
ren evclass.cpp evclass.cpp
ren execwait.cpp execwait.cpp
ren exists.cpp exists.cpp
ren extract.cpp extract.cpp
ren fifo.cpp fifo.cpp
ren fileclas.cpp fileclas.cpp
ren fillpart.cpp fillpart.cpp
ren fillshot.cpp fillshot.cpp
ren fix.cpp fix.cpp
ren fontclas.cpp fontclas.cpp
ren ftanalog.cpp ftanalog.cpp
ren ftiiclas.cpp ftiiclas.cpp
ren ftii_file.cpp ftii_file.cpp
ren ftii_parameters.cpp ftii_parameters.cpp
ren ftii_shot_data.cpp ftii_shot_data.cpp
ren ftime.cpp ftime.cpp
ren ftoasc.cpp ftoasc.cpp
ren genlist.cpp genlist.cpp
ren getshot.cpp getshot.cpp
ren get_ini.cpp get_ini.cpp
ren get_tc.cpp get_tc.cpp
ren gexedir.cpp gexedir.cpp
ren gpvar.cpp gpvar.cpp
ren hex.cpp hex.cpp
ren hourglas.cpp hourglas.cpp
ren iniclass.cpp iniclass.cpp
ren insalph.cpp insalph.cpp
ren is_empty.cpp is_empty.cpp
ren itoasc.cpp itoasc.cpp
ren killdir.cpp killdir.cpp
ren listbox.cpp listbox.cpp
ren log_file_string.cpp log_file_string.cpp
ren machcomp.cpp machcomp.cpp
ren machine.cpp machine.cpp
ren machname.cpp machname.cpp
ren marks.cpp marks.cpp
ren maximize.cpp maximize.cpp
ren mem.cpp mem.cpp
ren menu.cpp menu.cpp
ren mexists.cpp mexists.cpp
ren misc.cpp misc.cpp
ren monrun.cpp monrun.cpp
ren msgclas.cpp msgclas.cpp
ren nameclas.cpp nameclas.cpp
ren namecopy.cpp namecopy.cpp
ren names.cpp names.cpp
ren namesold.cpp namesold.cpp
ren optocontrol.cpp optocontrol.cpp
ren param.cpp param.cpp
ren part.cpp part.cpp
ren part_analog_sensor.cpp part_analog_sensor.cpp
ren path.cpp path.cpp
ren pexists.cpp pexists.cpp
ren plookup.cpp plookup.cpp
ren plotclas.cpp plotclas.cpp
ren plotsubs.cpp plotsubs.cpp
ren pointcl.cpp pointcl.cpp
ren postsec.cpp postsec.cpp
ren profiles.cpp profiles.cpp
ren pw.cpp pw.cpp
ren readline.cpp readline.cpp
ren rectclas.cpp rectclas.cpp
ren reverse.cpp reverse.cpp
ren ringcl.cpp ringcl.cpp
ren rjust.cpp rjust.cpp
ren runlist.cpp runlist.cpp
ren semaphor.cpp semaphor.cpp
ren sensor.cpp sensor.cpp
ren setpoint.cpp setpoint.cpp
ren shift.cpp shift.cpp
ren shotclas.cpp shotclas.cpp
ren sockcli.cpp sockcli.cpp
ren sockqueue.cpp sockqueue.cpp
ren startpar.cpp startpar.cpp
ren start_of_shift.cpp start_of_shift.cpp
ren stddown.cpp stddown.cpp
ren stparam.cpp stparam.cpp
ren stparam_new.cpp stparam_new.cpp
ren stpres.cpp stpres.cpp
ren strarray.cpp strarray.cpp
ren stringcl.cpp stringcl.cpp
ren structs.cpp structs.cpp
ren stsetup.cpp stsetup.cpp
ren temp_message.cpp temp_message.cpp
ren textlen.cpp textlen.cpp
ren textlist.cpp textlist.cpp
ren time.cpp time.cpp
ren timeclas.cpp timeclas.cpp
ren unitadj.cpp unitadj.cpp
ren units.cpp units.cpp
ren updown.cpp updown.cpp
ren visigrid.cpp visigrid.cpp
ren visiplot.cpp visiplot.cpp
ren warmupcl.cpp warmupcl.cpp
ren wclass.cpp wclass.cpp
ren winsubs.cpp winsubs.cpp
ren workclas.cpp workclas.cpp
ren writelin.cpp writelin.cpp
ren zero.cpp zero.cpp