#ifdef _MAIN_
TCHAR AChar    = TEXT( 'A' );
TCHAR BChar    = TEXT( 'B' );
TCHAR CChar    = TEXT( 'C' );
TCHAR DChar    = TEXT( 'D' );
TCHAR EChar    = TEXT( 'E' );
TCHAR FChar    = TEXT( 'F' );
TCHAR GChar    = TEXT( 'G' );
TCHAR HChar    = TEXT( 'H' );
TCHAR IChar    = TEXT( 'I' );
TCHAR JChar    = TEXT( 'J' );
TCHAR KChar    = TEXT( 'K' );
TCHAR LChar    = TEXT( 'L' );
TCHAR MChar    = TEXT( 'M' );
TCHAR NChar    = TEXT( 'N' );
TCHAR OChar    = TEXT( 'O' );
TCHAR PChar    = TEXT( 'P' );
TCHAR QChar    = TEXT( 'Q' );
TCHAR RChar    = TEXT( 'R' );
TCHAR SChar    = TEXT( 'S' );
TCHAR TChar    = TEXT( 'T' );
TCHAR UChar    = TEXT( 'U' );
TCHAR VChar    = TEXT( 'V' );
TCHAR WChar    = TEXT( 'W' );
TCHAR XChar    = TEXT( 'X' );
TCHAR YChar    = TEXT( 'Y' );
TCHAR ZChar    = TEXT( 'Z' );
TCHAR ACharLow = TEXT( 'a' );
TCHAR BCharLow = TEXT( 'b' );
TCHAR CCharLow = TEXT( 'c' );
TCHAR DCharLow = TEXT( 'd' );
TCHAR ECharLow = TEXT( 'e' );
TCHAR FCharLow = TEXT( 'f' );
TCHAR GCharLow = TEXT( 'g' );
TCHAR HCharLow = TEXT( 'h' );
TCHAR ICharLow = TEXT( 'i' );
TCHAR JCharLow = TEXT( 'j' );
TCHAR KCharLow = TEXT( 'k' );
TCHAR LCharLow = TEXT( 'l' );
TCHAR MCharLow = TEXT( 'm' );
TCHAR NCharLow = TEXT( 'n' );
TCHAR OCharLow = TEXT( 'o' );
TCHAR PCharLow = TEXT( 'p' );
TCHAR QCharLow = TEXT( 'q' );
TCHAR RCharLow = TEXT( 'r' );
TCHAR SCharLow = TEXT( 's' );
TCHAR TCharLow = TEXT( 't' );
TCHAR UCharLow = TEXT( 'u' );
TCHAR VCharLow = TEXT( 'v' );
TCHAR WCharLow = TEXT( 'w' );
TCHAR XCharLow = TEXT( 'x' );
TCHAR YCharLow = TEXT( 'y' );
TCHAR ZCharLow = TEXT( 'z' );

TCHAR AsterixChar       = TEXT( '*' );
TCHAR BackSlashChar     = TEXT( '\\' );
TCHAR ColonChar         = TEXT( ':' );
TCHAR CommaChar         = TEXT( ',' );
TCHAR CrChar            = TEXT( '\r' );
TCHAR DoubleQuoteChar   = TEXT( '\"' );
TCHAR EqualsChar        = TEXT( '=' );
TCHAR EtxChar           = TEXT( '\003' );
TCHAR ForwardSlashChar  = TEXT( '/' );
TCHAR LeftBracketChar   = TEXT( '[' );
TCHAR LeftCurlyBracket  = TEXT( '{' );
TCHAR LfChar            = TEXT( '\n' );
TCHAR MinusChar         = TEXT( '-' );
TCHAR NullChar          = TEXT( '\0' );
TCHAR PercentChar       = TEXT( '%' );
TCHAR PeriodChar        = TEXT( '.' );
TCHAR PlusChar          = TEXT( '+' );
TCHAR PoundChar         = TEXT( '#' );
TCHAR QuoteChar         = TEXT( '\'' );
TCHAR RightBracketChar  = TEXT( ']' );
TCHAR RightCurlyBracket = TEXT( '}' );
TCHAR SemiColonChar     = TEXT( ';' );
TCHAR SpaceChar         = TEXT( ' ' );
TCHAR TabChar           = TEXT( '\t' );
TCHAR TildaChar         = TEXT( '~' );
TCHAR UnderScoreChar    = TEXT( '_' );
TCHAR ZeroChar          = TEXT( '0' );
TCHAR OneChar           = TEXT( '1' );
TCHAR TwoChar           = TEXT( '2' );
TCHAR ThreeChar         = TEXT( '3' );
TCHAR FourChar          = TEXT( '4' );
TCHAR FiveChar          = TEXT( '5' );
TCHAR SixChar           = TEXT( '6' );
TCHAR SevenChar         = TEXT( '7' );
TCHAR StxChar           = TEXT( '\002' );
TCHAR EightChar         = TEXT( '8' );
TCHAR NineChar          = TEXT( '9' );

TCHAR AsterixString[] = TEXT( "*" );
TCHAR CommaString[]   = TEXT( "," );
TCHAR CrLfString[]    = TEXT( "\r\n" );
TCHAR EmptyString[]   = TEXT( "" );
TCHAR SpaceString[]   = TEXT( " " );
TCHAR StarDotStar[]   = TEXT( "*.*" );
#else

extern TCHAR AChar;
extern TCHAR BChar;
extern TCHAR CChar;
extern TCHAR DChar;
extern TCHAR EChar;
extern TCHAR FChar;
extern TCHAR GChar;
extern TCHAR HChar;
extern TCHAR IChar;
extern TCHAR JChar;
extern TCHAR KChar;
extern TCHAR LChar;
extern TCHAR MChar;
extern TCHAR NChar;
extern TCHAR OChar;
extern TCHAR PChar;
extern TCHAR QChar;
extern TCHAR RChar;
extern TCHAR SChar;
extern TCHAR TChar;
extern TCHAR UChar;
extern TCHAR VChar;
extern TCHAR WChar;
extern TCHAR XChar;
extern TCHAR YChar;
extern TCHAR ZChar;
extern TCHAR ACharLow;
extern TCHAR BCharLow;
extern TCHAR CCharLow;
extern TCHAR DCharLow;
extern TCHAR ECharLow;
extern TCHAR FCharLow;
extern TCHAR GCharLow;
extern TCHAR HCharLow;
extern TCHAR ICharLow;
extern TCHAR JCharLow;
extern TCHAR KCharLow;
extern TCHAR LCharLow;
extern TCHAR MCharLow;
extern TCHAR NCharLow;
extern TCHAR OCharLow;
extern TCHAR PCharLow;
extern TCHAR QCharLow;
extern TCHAR RCharLow;
extern TCHAR SCharLow;
extern TCHAR TCharLow;
extern TCHAR UCharLow;
extern TCHAR VCharLow;
extern TCHAR WCharLow;
extern TCHAR XCharLow;
extern TCHAR YCharLow;
extern TCHAR ZCharLow;

extern TCHAR AsterixChar;
extern TCHAR BackSlashChar;
extern TCHAR ColonChar;
extern TCHAR CommaChar;
extern TCHAR CrChar;
extern TCHAR DoubleQuoteChar;
extern TCHAR EtxChar;
extern TCHAR EqualsChar;
extern TCHAR ForwardSlashChar;
extern TCHAR LeftBracketChar;
extern TCHAR LeftCurlyBracket;
extern TCHAR LfChar;
extern TCHAR MinusChar;
extern TCHAR NullChar;
extern TCHAR PercentChar;
extern TCHAR PeriodChar;
extern TCHAR PlusChar;
extern TCHAR PoundChar;
extern TCHAR QuoteChar;
extern TCHAR RightBracketChar;
extern TCHAR RightCurlyBracket;
extern TCHAR SemiColonChar;
extern TCHAR SpaceChar;
extern TCHAR StxChar;
extern TCHAR TabChar;
extern TCHAR TildaChar;
extern TCHAR UnderScoreChar;
extern TCHAR ZeroChar;
extern TCHAR OneChar;
extern TCHAR TwoChar;
extern TCHAR ThreeChar;
extern TCHAR FourChar;
extern TCHAR FiveChar;
extern TCHAR SixChar;
extern TCHAR SevenChar;
extern TCHAR EightChar;
extern TCHAR NineChar;

extern TCHAR AsterixString[];
extern TCHAR CommaString[];
extern TCHAR CrLfString[];
extern TCHAR EmptyString[];
extern TCHAR SpaceString[];
extern TCHAR StarDotStar[];

#endif